# Generated by Django 6.0.4 on 2026-04-25 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('url', models.URLField(max_length=500, verbose_name='URL do Produto')),
                ('marketplace', models.CharField(choices=[('amazon', 'Amazon'), ('mercadolivre', 'Mercado Livre'), ('americanas', 'Americanas'), ('magalu', 'Magazine Luiza'), ('casasbahia', 'Casas Bahia'), ('outro', 'Outro')], max_length=20, verbose_name='Marketplace')),
                ('notify_whatsapp', models.BooleanField(default=False, verbose_name='Notificar no WhatsApp')),
                ('notify_telegram', models.BooleanField(default=False, verbose_name='Notificar no Telegram')),
                ('notify_promotion', models.BooleanField(default=True, verbose_name='Monitorar Promoções')),
                ('price_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Alvo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
